[package]
name = "wssnap-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
object_store = { version = "0.14.1", features = ["aws", "azure"] }
tokio = { version = "1.53.1", features = ["rt", "macros"] }
zstd = { version = "0.13.3", features = ["zstdmt"] }
futures = "0.3"
sha2 = "0.10"
libc = "0.2"
