[package]
name = "kloudlite-app"
version = "0.1.0"
edition = "2021"
license = "SSPL-1.0"

[lib]
name = "kloudlite_app"

[dependencies]
tracing = { workspace = true }
metrics = { workspace = true }
kloudlite-core = { path = "../core" }
kloudlite-storage = { path = "../storage" }
kloudlite-pulls = { path = "../pulls" }
tokio = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
slatedb = { workspace = true }
tempfile = { workspace = true }
