#!/usr/bin/env bash
# Keep every copy of Cloudflare's v4 edge ranges in this repo equal to the published list.
#
# WHY: the ranges are the origin lock. Three files carry them — `deploy/k3s/cloudflare-ips-v4.txt`
# (the source; `harden-node.sh` and the pool NSG rule are fed from it), the ingress-nginx Service
# (`loadBalancerSourceRanges`, the Azure LB's own admission) and the ingress-nginx ConfigMap
# (`proxy-real-ip-cidr`, which decides whose `CF-Connecting-IP` is believed). Hand-copying let
# them drift independently; this renders the last two FROM the first and exits non-zero when any
# of the three changed, so a CI run or an operator sees the drift instead of discovering it as a
# blocked edge. It never applies anything — the diff is the output.
#
# Usage: deploy/cf-sync.sh            fetch https://www.cloudflare.com/ips-v4, rewrite, diff
#        deploy/cf-sync.sh --no-fetch render from the committed txt only (offline)
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

LIST=deploy/k3s/cloudflare-ips-v4.txt
SVC=deploy/ingress-nginx-service.yaml
CM=deploy/ingress-nginx-config.yaml

if [ "${1:-}" != "--no-fetch" ]; then
  fetched=$(curl -sSf --max-time 20 https://www.cloudflare.com/ips-v4)
  # Only exact CIDRs, and not a short list. An empty or truncated response written through to the
  # Service would be an EMPTY `loadBalancerSourceRanges`, which Kubernetes reads as "everyone" —
  # the one failure mode that opens the origin rather than closing it.
  if ! printf '%s\n' "$fetched" | grep -qvE '^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$' \
     && [ "$(printf '%s\n' "$fetched" | wc -l)" -ge 10 ]; then
    printf '%s\n' "$fetched" > "$LIST"
  else
    echo "cf-sync: refusing to use an implausible ips-v4 response:" >&2
    printf '%s\n' "$fetched" >&2
    exit 2
  fi
fi

# Not `mapfile`: a stock macOS bash is 3.2 and this runs on laptops too.
cidrs=()
while IFS= read -r c; do [ -n "$c" ] && cidrs+=("$c"); done < "$LIST"
[ "${#cidrs[@]}" -ge 10 ] || { echo "cf-sync: $LIST has ${#cidrs[@]} entries, expected Cloudflare's full list" >&2; exit 2; }

{
  cat <<'EOF'
# GENERATED by deploy/cf-sync.sh from deploy/k3s/cloudflare-ips-v4.txt — do not hand-edit.
#
# The Cloudflare origin lock. Both HTTP hostnames are Cloudflare-proxied, so the ingress
# LoadBalancer must admit 80/443 from Cloudflare's edge only; the cloud controller turns this list
# into the NSG rule on the LB. Without it, anyone can skip the edge and hit the origin directly:
# the WAF and rate limits are bypassed and `CF-Connecting-IP`/`X-Real-IP` become attacker-chosen —
# which is exactly what the registry `limit-whitelist` trusts.
#
# This is a partial object on a Helm-managed Service, so it is applied server-side:
#   kubectl apply --server-side --force-conflicts -f deploy/ingress-nginx-service.yaml
# A Helm upgrade or reinstall of ingress-nginx drops the field; re-apply after either. Verify:
#   kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.spec.loadBalancerSourceRanges}'
# must be non-empty and equal to the list below. An EMPTY list means admit everyone.
#
# v4 only: the LB frontend is IPv4, so Cloudflare's v6 edges never reach it; add
# https://www.cloudflare.com/ips-v6 here the day it grows a v6 frontend. The git SSH LoadBalancer
# (`git.khost.dev`, not proxied) is a different Service and is untouched.
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  loadBalancerSourceRanges:
EOF
  for c in "${cidrs[@]}"; do echo "    - $c"; done
} > "$SVC"

joined=$(IFS=,; echo "${cidrs[*]}")
sed -i.bak "s|^  proxy-real-ip-cidr: .*|  proxy-real-ip-cidr: \"$joined\"|" "$CM" && rm -f "$CM.bak"
grep -q "proxy-real-ip-cidr: \"$joined\"" "$CM" || { echo "cf-sync: could not find the proxy-real-ip-cidr line in $CM" >&2; exit 2; }

# `git status`, not `git diff`: a freshly rendered manifest that is not yet tracked is drift too.
if [ -z "$(git status --porcelain -- "$LIST" "$SVC" "$CM")" ]; then
  echo "cf-sync: in sync (${#cidrs[@]} ranges)"
else
  git --no-pager status --short -- "$LIST" "$SVC" "$CM"
  git --no-pager diff HEAD -- "$LIST" "$SVC" "$CM"
  cat >&2 <<EOF

cf-sync: DRIFT — the files above were rewritten. Commit them, then re-apply the copies that live
outside git (each is a hand step, on purpose — this script touches no cluster):
  kubectl apply --server-side --force-conflicts -f $SVC -f $CM
  az network nsg rule update -g kloudlite-git-k3s --nsg-name k3s-nsg -n gateway-cloudflare \\
    --source-address-prefixes ${cidrs[*]}
  CF_CIDRS='$joined' on each pool node via harden-node.sh (deploy/k3s/README.md, Gateway step 6)
EOF
  exit 1
fi
