[package]
name = "kloudlite-registry"
version = "0.1.0"
edition = "2021"
license = "SSPL-1.0"

[lib]
name = "kloudlite_registry"

[dependencies]
tracing = { workspace = true }
metrics = { workspace = true }
kloudlite-core = { path = "../core" }
kloudlite-storage = { path = "../storage" }
kloudlite-app = { path = "../app" }
tokio = { workspace = true }
slatedb = { workspace = true }
sha2 = { workspace = true }
axum = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
form_urlencoded = { workspace = true }
rand = { workspace = true }
