[package]
name = "kloudlite-git-git"
version = "0.1.0"
edition = "2021"
license = "SSPL-1.0"

[lib]
name = "kloudlite_git_git"

[dependencies]
tracing = { workspace = true }
kloudlite-git-core = { path = "../core" }
kloudlite-git-storage = { path = "../storage" }
kloudlite-git-gitbase = { path = "../gitbase" }
kloudlite-git-app = { path = "../app" }
tokio = { workspace = true }
tokio-util = { workspace = true }
slatedb = { workspace = true }
russh = { workspace = true }
gix-odb = { workspace = true }
gix-pack = { workspace = true }
gix-object = { workspace = true }
gix-hash = { workspace = true }
gix-traverse = { workspace = true }
gix-features = { workspace = true }
imara-diff = { workspace = true }
serde = { workspace = true }
base64 = { workspace = true }
