/**
 * harness: opencode's own keybind table (`packages/tui/src/config/keybind.ts`, commit 5a83358),
 * as DATA. Their file imports `@opentui/core`, `@opentui/keymap` and `effect` — a terminal
 * runtime we do not run — so the chords and descriptions are transcribed and the dispatch stays
 * ours (`src/renderer/keys.ts`). `<leader>` is `ctrl+x`, as it is upstream.
 *
 * This is the source of truth for which chord means what; our own ⌘ keys are an ALIAS layer over
 * it, and the palette shows both.
 */
export const LEADER_DEFAULT = "ctrl+x";

export type Keybind = { command: string; keys: string; description: string };

export const KEYBINDS: Keybind[] = [
  { command: "app_exit", keys: "ctrl+c,ctrl+d,<leader>q", description: "Exit the application" },
  { command: "app_debug", keys: "none", description: "Toggle debug panel" },
  { command: "app_console", keys: "none", description: "Toggle console" },
  { command: "app_heap_snapshot", keys: "none", description: "Write heap snapshot" },
  { command: "app_toggle_animations", keys: "none", description: "Toggle animations" },
  { command: "app_toggle_file_context", keys: "none", description: "Toggle file context" },
  { command: "app_toggle_diffwrap", keys: "none", description: "Toggle diff wrapping" },
  { command: "app_toggle_paste_summary", keys: "none", description: "Toggle paste summary" },
  { command: "app_toggle_session_directory_filter", keys: "none", description: "Toggle session directory filtering" },
  { command: "command_list", keys: "ctrl+p", description: "List available commands" },
  { command: "help_show", keys: "none", description: "Open help dialog" },
  { command: "docs_open", keys: "none", description: "Open documentation" },
  { command: "diff_open", keys: "none", description: "Open diff viewer" },
  { command: "diff_close", keys: "escape,q", description: "Close diff viewer" },
  { command: "diff_toggle", keys: "enter,space", description: "Toggle diff viewer item" },
  { command: "diff_expand", keys: "right", description: "Expand diff viewer item" },
  { command: "diff_expand_all", keys: "E", description: "Expand all diff viewer folders" },
  { command: "diff_collapse", keys: "left", description: "Collapse diff viewer item" },
  { command: "diff_switch_focus", keys: "tab", description: "Switch diff viewer focus" },
  { command: "diff_next_hunk", keys: "]", description: "Jump to next diff hunk" },
  { command: "diff_previous_hunk", keys: "[", description: "Jump to previous diff hunk" },
  { command: "diff_next_file", keys: "n", description: "Jump to next diff file" },
  { command: "diff_previous_file", keys: "p", description: "Jump to previous diff file" },
  { command: "diff_toggle_file_tree", keys: "b", description: "Toggle diff viewer file tree" },
  { command: "diff_single_patch", keys: "s", description: "Toggle single patch view" },
  { command: "diff_switch_source", keys: "d", description: "Switch diff viewer source" },
  { command: "diff_toggle_view", keys: "v", description: "Toggle diff viewer split or unified view" },
  { command: "diff_help", keys: "?", description: "Show more diff viewer shortcuts" },
  { command: "editor_open", keys: "<leader>e", description: "Open external editor" },
  { command: "theme_list", keys: "<leader>t", description: "List available themes" },
  { command: "theme_switch_mode", keys: "none", description: "Switch between light and dark theme mode" },
  { command: "theme_mode_lock", keys: "none", description: "Lock or unlock theme mode" },
  { command: "sidebar_toggle", keys: "<leader>b", description: "Toggle sidebar" },
  { command: "scrollbar_toggle", keys: "none", description: "Toggle session scrollbar" },
  { command: "status_view", keys: "<leader>s", description: "View status" },
  { command: "debug_view", keys: "none", description: "View debug info" },
  { command: "session_export", keys: "<leader>x", description: "Export session to editor" },
  { command: "session_copy", keys: "none", description: "Copy session transcript" },
  { command: "session_move", keys: "none", description: "Move session" },
  { command: "session_new", keys: "<leader>n", description: "Create a new session" },
  { command: "session_list", keys: "<leader>l", description: "List all sessions" },
  { command: "session_timeline", keys: "<leader>g", description: "Show session timeline" },
  { command: "session_fork", keys: "none", description: "Fork session from message" },
  { command: "session_rename", keys: "ctrl+r", description: "Rename session" },
  { command: "session_delete", keys: "ctrl+d", description: "Delete session" },
  { command: "session_share", keys: "none", description: "Share current session" },
  { command: "session_unshare", keys: "none", description: "Unshare current session" },
  { command: "session_interrupt", keys: "escape", description: "Interrupt current session" },
  { command: "session_background", keys: "ctrl+b", description: "Background synchronous subagents" },
  { command: "session_compact", keys: "<leader>c", description: "Compact the session" },
  { command: "session_toggle_timestamps", keys: "none", description: "Toggle message timestamps" },
  { command: "session_toggle_generic_tool_output", keys: "none", description: "Toggle generic tool output" },
  { command: "session_queued_prompts", keys: "<leader>q", description: "Manage queued prompts" },
  { command: "session_child_first", keys: "<leader>down", description: "Go to first child session" },
  { command: "session_child_cycle", keys: "right", description: "Go to next child session" },
  { command: "session_child_cycle_reverse", keys: "left", description: "Go to previous child session" },
  { command: "session_parent", keys: "up", description: "Go to parent session" },
  { command: "session_pin_toggle", keys: "ctrl+f", description: "Pin or unpin session in the session list" },
  { command: "session_quick_switch_1", keys: "<leader>1", description: "Switch to session in quick slot 1" },
  { command: "session_quick_switch_2", keys: "<leader>2", description: "Switch to session in quick slot 2" },
  { command: "session_quick_switch_3", keys: "<leader>3", description: "Switch to session in quick slot 3" },
  { command: "session_quick_switch_4", keys: "<leader>4", description: "Switch to session in quick slot 4" },
  { command: "session_quick_switch_5", keys: "<leader>5", description: "Switch to session in quick slot 5" },
  { command: "session_quick_switch_6", keys: "<leader>6", description: "Switch to session in quick slot 6" },
  { command: "session_quick_switch_7", keys: "<leader>7", description: "Switch to session in quick slot 7" },
  { command: "session_quick_switch_8", keys: "<leader>8", description: "Switch to session in quick slot 8" },
  { command: "session_quick_switch_9", keys: "<leader>9", description: "Switch to session in quick slot 9" },
  { command: "stash_delete", keys: "ctrl+d", description: "Delete stash entry" },
  { command: "model_provider_list", keys: "ctrl+a", description: "Open provider list from model dialog" },
  { command: "model_favorite_toggle", keys: "ctrl+f", description: "Toggle model favorite status" },
  { command: "model_list", keys: "<leader>m", description: "List available models" },
  { command: "model_cycle_recent", keys: "f2", description: "Next recently used model" },
  { command: "model_cycle_recent_reverse", keys: "shift+f2", description: "Previous recently used model" },
  { command: "model_cycle_favorite", keys: "none", description: "Next favorite model" },
  { command: "model_cycle_favorite_reverse", keys: "none", description: "Previous favorite model" },
  { command: "mcp_list", keys: "none", description: "List MCP servers" },
  { command: "provider_connect", keys: "none", description: "Connect provider" },
  { command: "console_org_switch", keys: "none", description: "Switch console organization" },
  { command: "agent_list", keys: "<leader>a", description: "List agents" },
  { command: "agent_cycle", keys: "tab", description: "Next agent" },
  { command: "agent_cycle_reverse", keys: "shift+tab", description: "Previous agent" },
  { command: "variant_cycle", keys: "ctrl+t", description: "Cycle model variants" },
  { command: "variant_list", keys: "none", description: "List model variants" },
  { command: "messages_page_up", keys: "pageup,ctrl+alt+b", description: "Scroll messages up by one page" },
  { command: "messages_page_down", keys: "pagedown,ctrl+alt+f", description: "Scroll messages down by one page" },
  { command: "messages_line_up", keys: "ctrl+alt+y", description: "Scroll messages up by one line" },
  { command: "messages_line_down", keys: "ctrl+alt+e", description: "Scroll messages down by one line" },
  { command: "messages_half_page_up", keys: "ctrl+alt+u", description: "Scroll messages up by half page" },
  { command: "messages_half_page_down", keys: "ctrl+alt+d", description: "Scroll messages down by half page" },
  { command: "messages_first", keys: "ctrl+g,home", description: "Navigate to first message" },
  { command: "messages_last", keys: "ctrl+alt+g,end", description: "Navigate to last message" },
  { command: "messages_next", keys: "none", description: "Navigate to next message" },
  { command: "messages_previous", keys: "none", description: "Navigate to previous message" },
  { command: "messages_last_user", keys: "none", description: "Navigate to last user message" },
  { command: "messages_copy", keys: "<leader>y", description: "Copy message" },
  { command: "messages_undo", keys: "<leader>u", description: "Undo message" },
  { command: "messages_redo", keys: "<leader>r", description: "Redo message" },
  { command: "messages_toggle_conceal", keys: "<leader>h", description: "Toggle code block concealment in messages" },
  { command: "tool_details", keys: "none", description: "Toggle tool details visibility" },
  { command: "display_thinking", keys: "none", description: "Toggle thinking blocks visibility" },
  { command: "prompt_submit", keys: "none", description: "Submit prompt" },
  { command: "prompt_editor_context_clear", keys: "none", description: "Clear editor context" },
  { command: "prompt_skills", keys: "none", description: "Open skill selector" },
  { command: "prompt_stash", keys: "none", description: "Stash prompt" },
  { command: "prompt_stash_pop", keys: "none", description: "Pop stashed prompt" },
  { command: "prompt_stash_list", keys: "none", description: "List stashed prompts" },
  { command: "workspace_set", keys: "none", description: "Set workspace" },
  { command: "input_clear", keys: "ctrl+c", description: "Clear input field" },
  { command: "input_submit", keys: "return", description: "Submit input" },
  { command: "input_newline", keys: "shift+return,ctrl+return,alt+return,ctrl+j", description: "Insert newline in input" },
  { command: "input_move_left", keys: "left,ctrl+b", description: "Move cursor left in input" },
  { command: "input_move_right", keys: "right,ctrl+f", description: "Move cursor right in input" },
  { command: "input_move_up", keys: "up", description: "Move cursor up in input" },
  { command: "input_move_down", keys: "down", description: "Move cursor down in input" },
  { command: "input_select_left", keys: "shift+left", description: "Select left in input" },
  { command: "input_select_right", keys: "shift+right", description: "Select right in input" },
  { command: "input_select_up", keys: "shift+up", description: "Select up in input" },
  { command: "input_select_down", keys: "shift+down", description: "Select down in input" },
  { command: "input_line_home", keys: "ctrl+a", description: "Move to start of line in input" },
  { command: "input_line_end", keys: "ctrl+e", description: "Move to end of line in input" },
  { command: "input_select_line_home", keys: "ctrl+shift+a", description: "Select to start of line in input" },
  { command: "input_select_line_end", keys: "ctrl+shift+e", description: "Select to end of line in input" },
  { command: "input_visual_line_home", keys: "alt+a", description: "Move to start of visual line in input" },
  { command: "input_visual_line_end", keys: "alt+e", description: "Move to end of visual line in input" },
  { command: "input_select_visual_line_home", keys: "alt+shift+a", description: "Select to start of visual line in input" },
  { command: "input_select_visual_line_end", keys: "alt+shift+e", description: "Select to end of visual line in input" },
  { command: "input_buffer_home", keys: "home", description: "Move to start of buffer in input" },
  { command: "input_buffer_end", keys: "end", description: "Move to end of buffer in input" },
  { command: "input_select_buffer_home", keys: "shift+home", description: "Select to start of buffer in input" },
  { command: "input_select_buffer_end", keys: "shift+end", description: "Select to end of buffer in input" },
  { command: "input_delete_line", keys: "ctrl+shift+d", description: "Delete line in input" },
  { command: "input_delete_to_line_end", keys: "ctrl+k", description: "Delete to end of line in input" },
  { command: "input_delete_to_line_start", keys: "ctrl+u", description: "Delete to start of line in input" },
  { command: "input_backspace", keys: "backspace,shift+backspace", description: "Backspace in input" },
  { command: "input_delete", keys: "ctrl+d,delete,shift+delete", description: "Delete character in input" },
  { command: "input_undo", keys: "ctrl+-,super+z", description: "Undo in input" },
  { command: "input_redo", keys: "ctrl+.,super+shift+z", description: "Redo in input" },
  { command: "input_word_forward", keys: "alt+f,alt+right,ctrl+right", description: "Move word forward in input" },
  { command: "input_word_backward", keys: "alt+b,alt+left,ctrl+left", description: "Move word backward in input" },
  { command: "input_select_word_forward", keys: "alt+shift+f,alt+shift+right", description: "Select word forward in input" },
  { command: "input_select_word_backward", keys: "alt+shift+b,alt+shift+left", description: "Select word backward in input" },
  { command: "input_delete_word_forward", keys: "alt+d,alt+delete,ctrl+delete", description: "Delete word forward in input" },
  { command: "input_delete_word_backward", keys: "ctrl+w,ctrl+backspace,alt+backspace", description: "Delete word backward in input" },
  { command: "input_select_all", keys: "super+a", description: "Select all in input" },
  { command: "history_previous", keys: "up", description: "Previous history item" },
  { command: "history_next", keys: "down", description: "Next history item" },
  { command: "terminal_suspend", keys: "ctrl+z", description: "Suspend terminal" },
  { command: "terminal_title_toggle", keys: "none", description: "Toggle terminal title" },
  { command: "tips_toggle", keys: "<leader>h", description: "Toggle tips on home screen" },
  { command: "plugin_manager", keys: "none", description: "Open plugin manager dialog" },
  { command: "plugin_install", keys: "none", description: "Install plugin" },
  { command: "which_key_toggle", keys: "ctrl+alt+k", description: "Toggle which-key panel" },
  { command: "which_key_layout_toggle", keys: "ctrl+alt+shift+k", description: "Switch which-key layout" },
  { command: "which_key_pending_toggle", keys: "ctrl+alt+shift+p", description: "Toggle which-key pending preview" },
  { command: "which_key_group_previous", keys: "ctrl+alt+left,ctrl+alt+[", description: "Previous which-key group" },
  { command: "which_key_group_next", keys: "ctrl+alt+right,ctrl+alt+]", description: "Next which-key group" },
  { command: "which_key_scroll_up", keys: "ctrl+alt+up,ctrl+alt+p", description: "Scroll which-key up" },
  { command: "which_key_scroll_down", keys: "ctrl+alt+down,ctrl+alt+n", description: "Scroll which-key down" },
  { command: "which_key_page_up", keys: "ctrl+alt+pageup", description: "Page which-key up" },
  { command: "which_key_page_down", keys: "ctrl+alt+pagedown", description: "Page which-key down" },
  { command: "which_key_home", keys: "ctrl+alt+home", description: "Jump to first which-key binding" },
  { command: "which_key_end", keys: "ctrl+alt+end", description: "Jump to last which-key binding" },
];

/** The chord for a command, with `<leader>` expanded. */
export const chordOf = (command: string): string | undefined =>
  KEYBINDS.find((k) => k.command === command)?.keys.replace("<leader>", `${LEADER_DEFAULT} `);
